### ISSUE TITLE
Missing Res

### ISSUE THREAD

**Issue by TotoR115** [Gitjas/Solaufeins_Rescue_NPC#2]
The Res `C#SOLAU.WAV` does not exists:
https://github.com/Gitjas/Solaufeins_Rescue_NPC/blob/1e77e49ed1b7273ab8e06252b0ff24d30b883638/c%23solaufein/scripts/C%23solau.baf#L1097
https://github.com/Gitjas/Solaufeins_Rescue_NPC/blob/1e77e49ed1b7273ab8e06252b0ff24d30b883638/c%23solaufein/scripts/C%23solau.baf#L1144

The Res `IWDUST` does not exits. Could be replaced by `DWDUST`
https://github.com/Gitjas/Solaufeins_Rescue_NPC/blob/1e77e49ed1b7273ab8e06252b0ff24d30b883638/c%23solaufein/scripts/C%23Solau_AR2500.baf#L11

**Comment by Gitjas** [comment]
Thanks, fixed in v4.0
